version: "3.8"
services:
  fcreplay-tasker:
    image: fcreplay/image:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: "fcreplay tasker"
    environment:
      - CLIENT_SECRETS=/path/to/.client_secrets.json
      - CONFIG=/path/to/config.json
      - CPUS=4
      - DESCRIPTION_APPEND=/path/to/description_append.txt
      - IA=/path/to/.ia
      - FCREPLAY_NETWORK=some_docker_network,some_other_docker_network
      - MAX_INSTANCES=1
      - MEMORY=4g
      - ROMS=/path/to/ROMs
      - YOUTUBE_UPLOAD_CREDENTIALS=/path/to/.youtube-upload-credentials.json
      - AVI_TEMP_DIR=/path/to/large/avi_storage_temp
    volumes:
      - /path/to/config.json:/root/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/large/avi_storage_temp:/avi_storage_temp
    networks:
      - postgres
      - world
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

networks:
  world:
  postgres:
    internal: true

volumes:
  postgres:
