---
- name: Setup fcrecorder machine
  hosts: all
  become: True
  tasks:
    - name: Install obs-repo
      yum:
        name: "{{packages}}"
      vars:
        packages:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm 
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

    - name: Install packages
      yum:
        name: "{{packages}}"
      vars:
        packages:
          - alsa-utils
          - chkconfig
          - cmake
          - firewalld
          - gcc
          - git
          - i3
          - jq
          - libpq-devel
          - maim
          - obs-studio
          - pavucontrol
          - portaudio
          - portaudio-devel
          - pulseaudio
          - pulseaudio-libs
          - python3
          - python3-devel
          - rsync
          - tmux
          - unzip
          - vim
          - wget
          - wine.i686
          - x11vnc
          - xinit
          - xorg-x11-drv-dummy
          - xterm

    - name: install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: VNC Rules
      firewalld:
        port: 5900/tcp
        immediate: yes
        permanent: yes
        state: enabled

    - name: Create group
      group:
        name: fcrecorder
        state: present

    - name: Create user
      user:
        name: fcrecorder
        comment: FC Recorder
        create_home: True
        home: /home/fcrecorder
        shell: /bin/bash
        group: fcrecorder
        groups: pulse,pulse-access,input

    - name: Clone fcreplay
      git:
        repo: https://github.com/glisignoli/fcreplay.git
        dest: /home/fcrecorder/fcreplay_install
      become_user: fcrecorder
      become: True

    - name: Make install directory
      file:
        path: /home/fcrecorder/fcreplay
        state: directory
        mode: '0750'
      become_user: fcrecorder
      become: True

    - name: Create venv
      command: python3 -m venv ./venv
      args:
        chdir: /home/fcrecorder/fcreplay
      become_user: fcrecorder
      become: True

    - name: Install fcreplay
      shell: |
        cd /home/fcrecorder/fcreplay
        source ./venv/bin/activate
        cd /home/fcrecorder/fcreplay_install
        python setup.py install
      become_user: fcrecorder
      become: True

    - name: Clone youtube-upload
      git:
        repo: https://github.com/tokland/youtube-upload.git
        dest: /home/fcrecorder/youtube-upload
      become_user: fcrecorder
      become: True

    - name: Install youtube-upload
      shell: |
        cd /home/fcrecorder/fcreplay
        source ./venv/bin/activate
        pip install --upgrade google-api-python-client oauth2client progressbar2 scikit-build
        cd /home/fcrecorder/youtube-upload
        python setup.py install
      become_user: fcrecorder
      become: True

    - name: Copy config.json
      copy:
        src: ./config.json
        dest: /home/fcrecorder/fcreplay/config.json
        owner: fcrecorder
        group: fcrecorder
        mode: '0600'
      ignore_errors: yes

    - name: Copy description append
      copy:
        src: ./description_append.txt
        dest: /home/fcrecorder/fcreplay/description_append.txt
        owner: fcrecorder
        group: fcrecorder
        mode: '0640'
      ignore_errors: yes

    - name: Copy youtube upload credentials
      copy:
        src: ./.youtube-upload-credentials.json
        dest: /home/fcrecorder/.youtube-upload-credentials.json
        owner: fcrecorder
        group: fcrecorder
        mode: '0600'
      ignore_errors: yes

    - name: Copy google api client secrets
      copy:
        src: ./.client_secrets.json
        dest: /home/fcrecorder/.client_secrets.json
        owner: fcrecorder
        group: fcrecorder
        mode: '0600'
      ignore_errors: yes

    - name: Copy archive.org secrets
      copy:
        src: ./.ia
        dest: /home/fcrecorder/.ia
        owner: fcrecorder
        group: fcrecorder
        mode: '0600'
      ignore_errors: yes

    - name: Copy xorg.conf
      copy:
        src: ./files/xorg.conf
        dest: /etc/X11/
        owner: root
        group: root
        mode: '0644'

    - name: Copy Xwrapper
      copy:
        src: ./files/Xwrapper.config
        dest: /etc/X11/
        owner: root
        group: root
        mode: '0644'

    - name: Create xinitrc
      copy:
        content: exec i3
        dest: /home/fcrecorder/.xinitrc
        owner: fcrecorder
        group: fcrecorder
        mode: '0640'

    - name: Create i3 config directory
      command: mkdir -p /home/fcrecorder/.config/i3
      become_user: fcrecorder
      become: True

    - name: Copy i3 config
      copy:
        src: ./files/i3_config
        dest: /home/fcrecorder/.config/i3/config
        owner: fcrecorder
        group: fcrecorder
        mode: '0664'

    - name: Copy the gcloudlauncher
      copy:
        src: ./files/gcloudlauncher.sh
        dest: /usr/local/bin/gcloudlauncher.sh
        owner: fcrecorder
        group: fcrecorder
        mode: '0750'

    - name: Copy the startup service file
      copy:
        src: ./files/fcrecord.service
        dest: /usr/lib/systemd/system/fcrecord.service
        owner: root
        group: root
        mode: '0664'

    - name: Copy the startup file
      copy:
        src: ./files/startup.sh
        dest: /home/fcrecorder/startup.sh
        owner: fcrecorder
        group: fcrecorder
        mode: '0750'

    - name: Copy fcreplaychat launcher
      copy:
        src: ./files/chatlauncher.sh
        dest: /usr/local/bin/chatlauncher.sh
        owner: fcrecorder
        group: fcrecorder
        mode: '0750'

    - name: Copy fcreplaychat service
      copy:
        src: ./files/fcreplaychat.service
        dest: /usr/lib/systemd/system/fcreplaychat.service
        owner: root
        group: root
        mode: '0644'

    - name: Install cloud logging config
      yum:
        name: google-fluentd-catch-all-config
        state: latest
      when: gcloud

    - name: Add google cloud fcreplay logging
      copy:
        src: ./files/google-cloud-fcreplay-looging.conf
        dest: /etc/google-fluentd/config.d/
        owner: root
        group: root
        mode: '0640'
      when: gcloud

    - name: Enable google cloud logging systemd service
      service:
        name: google-fluentd
        state: started
        enabled: yes
      when: gcloud

    - name: Autostart recording for gcloud
      replace:
        path: /home/fcrecorder/.config/i3/config
        regexp: '^# exec "xterm'
        replace: 'exec "xterm'
      become: True
      become_user: fcrecorder
      when: gcloud

    - name: Create config directory
      file:
        path: /home/fcrecorder/.config
        state: directory
        mode: 0750
      become: True
      become_user: fcrecorder

    - name: Copy obs config
      copy:
        src: ./files/obs-studio
        dest: /home/fcrecorder/.config/
      become: True
      become_user: fcrecorder

    - name: Copy fightcade2
      synchronize:
        src: "{{ FC2_PATH }}"
        dest: /home/fcrecorder/fcreplay/
      become: True
      become_user: fcrecorder
      ignore_errors: true

    - name: Set fbneo scanlines on default config
      replace:
        path: /home/fcrecorder/fcreplay/Fightcade/emulator/fbneo/config/fcadefbneo.default.ini
        regexp: '^bVidScanlines 1'
        replace: 'bVidScanlines 0'
      become: True
      become_user: fcrecorder


    - name: Set fbneo scanlines on config
      replace:
        path: /home/fcrecorder/fcreplay/Fightcade/emulator/fbneo/config/fcadefbneo.ini
        regexp: '^bVidDX9Scanlines 1'
        replace: 'bVidDX9Scanlines 0'
      become: True
      become_user: fcrecorder
      ignore_errors: true

    - name: Enable fcrecord service
      service:
        name: fcrecord
        state: stopped
        enabled: true
      when: gcloud
